version: "3.8"

services:
  pong-react-app:
    build: .
    ports:
      - "3001:80"
    environment:
      - NGINX_VERSION=1.29.0
      - NJS_VERSION=0.9.0
    deploy:
      resources:
        limits:
          memory: 1846M
    restart: unless-stopped
