version: "3.8"

services:
  backend:
    build: .
    container_name: pong_backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    labels:
      - com.casaplatform.app=pong_backend
    restart: unless-stopped