version: "3.8"

services:
  backend:
    build: .
    container_name: pong_backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    labels:
      - com.casaplatform.app=pong_backend
    restart: unless-stopped